#!/usr/bin/env bash
set -euo pipefail

if [[ -x "$HOME/.rubies/ruby-3.1.3/bin/bundle" ]]; then
  BUNDLE_BIN="$HOME/.rubies/ruby-3.1.3/bin/bundle"
else
  BUNDLE_BIN="bundle"
fi

export BUNDLE_PATH="vendor/bundle"
export BUNDLE_APP_CONFIG=".bundle"

"$BUNDLE_BIN" exec jekyll serve --drafts --incremental
